[theme]
base = "light"
primaryColor = "#141412"
backgroundColor = "#f4f2ec"
secondaryBackgroundColor = "#fbfaf6"
textColor = "#141412"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
